version: '3.9'

services:
  dealscout-listener:
    container_name: dealscout-listener
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - stack.env
    volumes:
      - dealscout_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dealscout_data: